### PR TITLE
block button added

### LINKED ISSUE #289: Add Block Button class
Add a class that would change any button to a block button. We should also add a note about it, maybe in the "How to Use" section with an example (based on Basic Button).

This should work on any button type, so give it a basic class name something like "block-btn"

### PR DESCRIPTION
**Pull request by zahra-abdullah**
Issue: #289

### CODE REVIEW

**Comment by zahra-abdullah** [comment]
Hi @shahednasser! 
I was thinking, now we have one more basic button design, how about add basic buttons, rounded buttons and block buttons in tabs, so users dont have to scroll down to see different button designs!! Let me know what you think. I can work on it as a separate fix

**Review by shahednasser — CHANGES_REQUESTED** [review]
It looks great just one note:

1. Hinge block buttons are overlapping with the text classes under it. You can fix this by adding in `assets/css/index.css` a rule something like this:
```
#hinge .button-container .sbtn {
margin-bottom: 1.7em;
}
```
it might require `!important` so you can add it if necessary.

**Comment by shahednasser** [comment]
> Hi @shahednasser!
> I was thinking, now we have one more basic button design, how about add basic buttons, rounded buttons and block buttons in tabs, so users dont have to scroll down to see different button designs!! Let me know what you think. I can work on it as a separate fix

I like this idea. Please work on it.

**Comment by zahra-abdullah** [comment]
> It looks great just one note:
> 
> 1. Hinge block buttons are overlapping with the text classes under it. You can fix this by adding in `assets/css/index.css` a rule something like this:
> 
> ```
> #hinge .button-container .sbtn {
> margin-bottom: 1.7em;
> }
> ```
> 
> it might require `!important` so you can add it if necessary.

updated! thanks for the hint! Please review!

**Comment by shahednasser** [comment]
Great work thank you!

**Pull request merged**
