### PR TITLE
added trace button

### PR DESCRIPTION
**Pull request by Kazeno21**
Issue:
#420

### CODE REVIEW

**Comment by Kazeno21** [comment]
@shahednasser, can you please merge it? the button works as specified in the issue. No merge conflicts this time :)

**Comment by shahednasser** [comment]
Hi @Kazeno21 I'm sorry but it looks nothing like the described issue. Please fix it to match the issue

**Comment by Kazeno21** [comment]
@shahednasser , can you please elaborate what else you need ? I would start working on those required changes

**Comment by shahednasser** [comment]
@Kazeno21 please go back to the issue you were assigned to. It says the button on hover should trace the border from start to end. Also, the buttons you made look very different from the rest of the website and there's a problem with the width and height of them.

**Comment by Kazeno21** [comment]
> @Kazeno21 please go back to the issue you were assigned to. It says the button on hover should trace the border from start to end. Also, the buttons you made look very different from the rest of the website and there's a problem with the width and height of them.

got it! thanks for the help

**Pull request closed without merging**
