### PR TITLE
scroll-top btn added

### PR DESCRIPTION
**Pull request by Pratyush-Saxena**
Scroll to top button added , visit https://pratyush-saxena.github.io/sbuttons/ to see the changes

Issue: #27 resolved

### CODE REVIEW

**Comment by Pratyush-Saxena** [comment]
added sroll-to-top button

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great work! Just a few changes please:

1. Make the button's width/height 40px, the border-radius 50%, and the color of the icon white
2. Put the button on the right side of the page
3. When the page first opens you can see the button. If you can put the code for the `scroll` event in a function and call it on page load that would be great. You can see an example of what I mean with the `checkNavbar` and `checkActiveCategory` functions.

**Comment by Pratyush-Saxena** [comment]
@shahednasser , I have made Changes as per your request pls check it out
https://pratyush-saxena.github.io/sbuttons/

**Comment by shahednasser** [comment]
Great! There's something still pending which is that the `.scroll-top` element is still appearing on page load.

https://github.com/shahednasser/sbuttons/blob/1042d9cc7d0c52c620fffc38c91f39d8c794116a/assets/js/index.js#L66-L70

Move this part into a function under the `checkNavbar` function. Name the function `checkScrollTop` or anything you feel fitting. Then, call the function under the `checkNavbar` and `checkActiveCategory` functions on lines 57 and 61:

https://github.com/shahednasser/sbuttons/blob/1042d9cc7d0c52c620fffc38c91f39d8c794116a/assets/js/index.js#L56-L62

There's already a scroll event so let's not create an extra one.

Also, please change the `font-size` for `.scroll-top i` to 35px and set `right` for `.scroll-top` to 20px instead of setting `left` (remove the left property)

**Comment by Pratyush-Saxena** [comment]
@shahednasser .....i have done all the changes stated above  this time  ..just one thing is there that I m unable to fix....is that.. As u asked me to set right property for .scroll-to instead of left.....so I tried to use float : right which isn't working....that why I used left margin to display the button in right side of window

**Comment by shahednasser** [comment]
ok @Pratyush-Saxena no problem. Keep the `left` for now and commit the changes you made.

**Comment by Pratyush-Saxena** [comment]
@shahednasser hope now its all done in the way you want....

**Comment by shahednasser** [comment]
Great @Pratyush-Saxena thank you

@all-contributors please add @Pratyush-Saxena for code

**Pull request merged**
