### PR TITLE
added tooltip- on copying class names

### PR DESCRIPTION
**Pull request by Hrishi-Raj**
- Added Bootstrap Tooltip, triggered by click on class names below the Button & automatically hides after a interval of 1500ms.

Screenshot from 2020-09-09 00-18-24

Attached Screenshot is showing tooltip triggered on click. (See first button in the image)
### Issue: Add message on clicking class names #48

### CODE REVIEW

**Review by shahednasser — COMMENTED** [review]
Great work! I just need you to make minor changes:  

1. Make the tooltip appear on the bottom (not overshadowing the button). 
2. Add a comment before `setTimeout` saying "Hide tooltip"

**Comment by Hrishi-Raj** [comment]
Thank You @shahednasser 
I have made the mentioned changes. Looking forward to your suggestions.

**Review by shahednasser — CHANGES_REQUESTED** [review]
Your work was good, however, I couldn't merge your work because your `index.html` conflicted with the master branch. Please just re-add poppers and bootstrap JS files to `index.html` and make sure they're below jquery. Don't add "tooltip" attributes to the elements as it is unnecessary with javascript initialization.

**Comment by Hrishi-Raj** [comment]
I just rebased my branch and merged the branches. Will this be fine?

**Comment by shahednasser** [comment]
Great! Thank you.

@all-contributors please add @Hrishi-Raj for code

**Pull request merged**
