### PR TITLE
Click Buttons updated with click effects

### LINKED ISSUE #42: Click button animation style
**CHANGE IN CLICK BUTTON STYLE**
I guess Click button that u have made will look much better if it would be like
this one :
click_button
rather than this one :
click_2

**Additional notes**

### PR DESCRIPTION
**Pull request by Pratyush-Saxena**
@shahednasser i have resolved #42 ...By improving  click buttons..

### CODE REVIEW

**Comment by Pratyush-Saxena** [comment]
@shahednasser ....i m trying to resolve this whatever conflict ...in subuttons.min.css ....can you help me in this

**Comment by shahednasser** [comment]
Hello! I think you've made changes directly to `dist/sbuttons.css` and that's not how it should be done. You need to make the changes in `src/components/animated/_click.less` then run `npm run compile`

**Comment by Pratyush-Saxena** [comment]
> npm run compile

@shahednasser  Do i have to make changes only in _click.less or in sbuttons.css too??

**Comment by shahednasser** [comment]
If you're making changes for the click button only then yes just `_click.less`

**Comment by shahednasser** [comment]
The problem is that your branch is way behind the master branch. You need to sync your master branch to this master branch. Learn more about it in the [contribution guide] (https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) in step 4 of pull requests

**Comment by Pratyush-Saxena** [comment]
@shahednasser 
shot
is the written text a part pf code or some mistyped stuff...Coz its showing error in my vs_code compiler

**Comment by Pratyush-Saxena** [comment]
> The problem is that your branch is way behind the master branch. You need to sync your master branch to this master branch. Learn more about it in the [contribution guide] (https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) in step 4 of pull requests

After doing this ..its throwing an error on pushing ...
erro

**Comment by shahednasser** [comment]
I'm not sure what's happening on your side, but maybe the easiest approach right now is to fork the repository again and add your changes to `_click.less` then compiling

**Comment by Pratyush-Saxena** [comment]
@shahednasser  i have created new PR #87 ...Pls have a look

**Pull request closed without merging**
