### PR TITLE
changes

### PR DESCRIPTION
**Pull request by codeSalazar12**
Changes to the index.html file 

Issue:In the download button section of the website, the buttons' text was "Button" I changed it to "Download"

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
It seems like there are some problems with the spacing in the file. It could be because of the editor you're using but I'm not sure. Please fix it before we can merge your work. 

Check the "Files changed" to see what the spacing issue is.

**Comment by codeSalazar12** [comment]
okay sure

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great but there are still two things that need fixing: 
1. There's still spacing between `<html>` and `<head>` so please remove it.
2. Fix the line indentation. You can see what I mean if you look at `<html>` and `<head>`. If you have trouble with this one then leave it for now.

**Comment by codeSalazar12** [comment]
I think I made the all requirements kindly check

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great, all the spacings are fixed but I think you forgot to change the text for the rounded buttons. Please change the text to "Download" for the rounded buttons too.

**Comment by codeSalazar12** [comment]
Okay now please check.

**Comment by shahednasser** [comment]
Great! Thank you so much for your work.

@all-contributors please add @codeSalazar12 for code

**Pull request merged**
