### PR TITLE
i design four favicon in the folder select any

### PR DESCRIPTION
**Pull request by Mancancode**
Issue:

the folder "favicondesign" contains 4 different favicons you can choose from for the  "sbutton"  favicon, I hope this helps.

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @Mancancode thank you for your work. We have accepted someone else's work but I still appreciate your contribution so I will add you to our contributors

**Comment by shahednasser** [comment]
@all-contributors please add @Mancancode for design

**Comment by Mancancode** [comment]
Wow, thanks a lot I really appreciate 👏👏

**Comment by Mancancode** [comment]
Please can I get the #sButton twitter handle, to follow. Thanks

**Comment by shahednasser** [comment]
@Mancancode we don't have a twitter account

**Comment by Mancancode** [comment]
It won't be bad if we have one. The future is bright and I see #sButton getting bigger, and as a contributor, I will support in making it a house hold name among developers around the world.

**Pull request closed without merging**
