### PR TITLE
Login with apple button added , Instagram button bug fixed , social b…

### PR DESCRIPTION
**Pull request by dsnehasish74**
Screenshot (163)
…utton ui make userfriendly

Issue: https://github.com/shahednasser/sbuttons/issues/22
https://github.com/shahednasser/sbuttons/issues/271
https://github.com/shahednasser/sbuttons/issues/270

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
It all looks good. As for the changes in `buttons-examples.js` I know you made the changes for better UI, but please leave it as it was for now. And please make sure to add "Apple" in the correct alphabetical order.

**Comment by dsnehasish74** [comment]
ok the I am doing it another time

**Comment by dsnehasish74** [comment]
I add another pull request with the change what you want ............ plz merge that

**Comment by dsnehasish74** [comment]
https://github.com/shahednasser/sbuttons/pull/299

**Pull request closed without merging**
