### PR TITLE
Create _trace.less

### PR DESCRIPTION
**Pull request by Kazeno21**
trace button

Issue: Issue no. 420 - trace button completed

### CODE REVIEW

**Comment by Kazeno21** [comment]
added _trace.less

**Comment by shahednasser** [comment]
Hi @Kazeno21 you've added a trace button but there's still more to do. You need to import the file in `src/components/_animated.less` and then add it in `assets/js/buttons-examples.js` under "Animated". Lastly you need to compile your code to show the changes. Please read the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more details.

**Comment by Kazeno21** [comment]
> Hi @Kazeno21 you've added a trace button but there's still more to do. You need to import the file in `src/components/_animated.less` and then add it in `assets/js/buttons-examples.js` under "Animated". Lastly you need to compile your code to show the changes. Please read the [contributing guidelines](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) for more details.

ok cool. will work on that!

**Comment by Kazeno21** [comment]
@shahednasser, i have done the required changes. can you please help me out?

**Comment by shahednasser** [comment]
Hi @Kazeno21 I've checked your work and I'm not really sure what you've done. Can you confirm that it's working as you want it to? Please look back at the issue description and make sure you're implementing the idea correctly.

**Comment by Kazeno21** [comment]
> Hi @Kazeno21 I've checked your work and I'm not really sure what you've done. Can you confirm that it's working as you want it to? Please look back at the issue description and make sure you're implementing the idea correctly.

it is doing what i want to but there is some merge conflict. can you please try to resolve that?

**Comment by Kazeno21** [comment]
@shahednasser, it does work as i had anticipated but the pr has some merge conflicts. can you please resolve those?

**Pull request closed without merging**
