### PR TITLE
add cracking neon button idea

### PR DESCRIPTION
**Pull request by EmpalGentong**
Adding new Idea "cracking neon button idea"

Issue:https://github.com/shahednasser/sbuttons/issues/96

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @EmpalGentong thank you for your contribution! I'm not sure I understand what you mean by this button. Can you explain more?

**Comment by EmpalGentong** [comment]
> Hi @EmpalGentong thank you for your contribution! I'm not sure I understand what you mean by this button. Can you explain more?

its like neon animated button and when the button clicked the neon turn off and cracked

**Comment by shahednasser** [comment]
I'm still not sure what that means to be honest but I'll add this in case you or someone else would like to implement it. Maybe I can understand it better then!

@all-contributors please add @EmpalGentong for idea

**Comment by shahednasser** [comment]
@all-contributors please add @EmpalGentong for idea

**Pull request merged**
