### PR TITLE
add some new social login button

### PR DESCRIPTION
**Pull request by isonnymichael**
Add instagram, linkedin, twitter, weibo social button

Issue: Add Social Login buttons under "Social Buttons" type

### CODE REVIEW

**Comment by isonnymichael** [comment]
What mean format(prettier) / Prettier (pull_request) ? I don't get it

**Review by shahednasser — CHANGES_REQUESTED** [review]
Can you please remove the border for instagram? Make sure to run compile again once you're done. Don't worry about prettier.

**Comment by isonnymichael** [comment]
I've removed the instagram border, but I'm sorry if I made some weird commit because I'm still learning about git. (I think I make commit a few times, because I got conflict and I try to push but I dont it's work or not)

**Comment by shahednasser** [comment]
Great! Thank you

**Pull request merged**
