### PR TITLE
added rounded social buttons

### PR DESCRIPTION
**Pull request by Neeraj3508**
Issue:

### CODE REVIEW

**Comment by Neeraj3508** [comment]
can u help me with this branch conflict?

**Comment by Neeraj3508** [comment]
@shahednasser

**Comment by shahednasser** [comment]
Please merge the newest changes from the master, as there are some conflicts that can't be resolved.

**Comment by Neeraj3508** [comment]
should i create another pull-request and close this one or can i just discard this conflicting file and create another commit
?

**Comment by shahednasser** [comment]
You can discard the conflicting file

**Comment by Neeraj3508** [comment]
creating this pull request again don't know what's happening

**Comment by Neeraj3508** [comment]
i just sae that the file which was conflicting had been removed from original sbuttons repository

**Comment by Neeraj3508** [comment]
so can u tell me if if need to do it all over again or will this request be merged as i had deleted the conflicting files.

**Comment by shahednasser** [comment]
You don't need to do it all over again. I'll look into your work and merge it if I find everything is ok!

**Comment by Neeraj3508** [comment]
ok do update me if there are issues you can discard this and i will do it again

**Comment by shahednasser** [comment]
It seems that you deleted the branch and unfortunately I can't see how the changes you made look like. Can you show me a screenshot of how it should be at least?

**Comment by Neeraj3508** [comment]
https://drive.google.com/file/d/17f-U46BcNgXi0kuxy7kZyCIsU8OestwK/view?usp=drivesdk
https://drive.google.com/file/d/17b0ZjAUGQwXiXkvAHoF4VBYm3OCwbG2O/view?usp=drivesdk

**Comment by Neeraj3508** [comment]
I will push these changes again and then you can check also the conflict was due to the file sbutton.min.css was deleted from main repository and i made a pull request before that

**Comment by shahednasser** [comment]
I meant a screenshot of how the buttons should look like. I can see the changes you made in code but since there's no repository, I can't clone it to see it in action

**Comment by Neeraj3508** [comment]
my code is deleted just give me some time maybe an hour or half i wil update them and then send you screenshots and then if you think about about changes you can tell me

**Comment by Neeraj3508** [comment]
You had removed that sbutton.min.css where should i put that code into?

**Comment by shahednasser** [comment]
Make sure your repo is up to date with this one, then just make changes in the less files and run "npm run compile". We don't need "sbuttons.min.css" anymore.

**Comment by Neeraj3508** [comment]
Screenshot 2020-09-26 at 11 53 06 PM
Here it is

**Comment by Neeraj3508** [comment]
Please  check these then after your approval i will push these changes

**Comment by shahednasser** [comment]
Looks great, but I think the font shouldn't change (should remain as it is now).

Please push the changes.

**Pull request closed without merging**
