### PR TITLE
fixed a bug with instagram text on site

### PR DESCRIPTION
**Pull request by Neeraj3508**
Issue:

### CODE REVIEW

**Comment by shahednasser** [comment]
I'm not sure what the bug you're trying to fix is. Please explain more on what the bug is and what you did.

**Comment by Neeraj3508** [comment]
On website it the labels for instagram buttons were swapped.

**Comment by shahednasser** [comment]
Great thank you!

@all-contributors please add @Neeraj3508 for bug

**Comment by shahednasser** [comment]
@all-contributors please add @dsnehasish74 for bug

**Pull request merged**
