### PR TITLE
Add whatsapp button

### PR DESCRIPTION
**Pull request by quangpro1610**
add new WhatsApp button

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
I like the button but I don't think there's such thing as "Login with whatsapp" so how about changing it to something like "Chat on Whatsapp"

**Comment by shahednasser** [comment]
@quangpro1610 is there a login with Bitbucket functionality? We don't want to add anything that doesn't actually exist.

**Comment by quangpro1610** [comment]
> @quangpro1610 is there a login with Bitbucket functionality? We don't want to add anything that doesn't actually exist.

Have you used Bitbucket before?  It is similar to GitHub
Read more: https://bitbucket.org/

**Comment by shahednasser** [comment]
I know bitbucket but can you go on a different website and choose to "Login with Bitbucket"?

**Pull request closed without merging**
