### PR TITLE
Play game button

### LINKED ISSUE #428: [BUTTON IDEA]: Play Game Button
**1. Name of button**: Play Game Button

**2. Description**: A play game button which has a game controller shape

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**submitted by**: @Nicolakacha

### PR DESCRIPTION
**Pull request by zilyukina**
closes #428

pixel art reference: http://pixelartmaker.com/art/a39449a263e0081

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @zilyukina someone is assigned for this issue but because you took a different approach and it looks really nice, I like what you've done. Please next time choose an issue that is not assigned to anyone.

I think what you have done falls under another category that we're still working on so I'm gonna hold off merging this until that is ready. I might ask for a few changes then. I'll let you know!

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hi @zilyukina you now can add this button under the "Special" Category. Please change the folder you put it in (instead of icon it should be special now) and import it in _special.less as well. Make sure to compile after you're done and make the changes in buttons-examples.js. You should place it in the correct alphabetical order under "Special". 

Please update your forked repository to the current changes to start working on it.

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @zilyukina for code and idea

**Comment by zilyukina** [comment]
> Hi @zilyukina someone is assigned for this issue but because you took a different approach and it looks really nice, I like what you've done. Please next time choose an issue that is not assigned to anyone.
> 
> I think what you have done falls under another category that we're still working on so I'm gonna hold off merging this until that is ready. I might ask for a few changes then. I'll let you know!

Thank you so mush! I was so excited that just forgot about request for assignment :sweat_smile:

**Pull request merged**
