### PR TITLE
added dark mode buttons under new special category

### PR DESCRIPTION
**Pull request by Neeraj3508**
added two new classes lightmode and darkmode for respective buttons under special category as mentioned in buttonIdeas.md

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you @Neeraj3508 for your work but someone is already working on the dark mode toggle in #229 . Let me know if you would like to work on another special button as I have some pointers on the js file. If not, then please close this PR.

**Comment by Neeraj3508** [comment]
Ok but please assign me this time as previously also i had worked on 2 issues but by the  time of merging they had been resolved.

**Comment by shahednasser** [comment]
Can you please create a new issue with what idea you would like to work on so I can let you know if it has been taken and if not then I can assign you? Thank you.

**Comment by Neeraj3508** [comment]
And shall i leave this opened if #229 will not be solved then you can consider this otherwise you can reject this if issue will be solved.

**Pull request closed without merging**
