### PR TITLE
Added Tagline Under Logo ( Issue: #8)

### PR DESCRIPTION
**Pull request by SeshaiHari**
Added a tagline under the logo saying 'Made with ❤︎'.

Issue: #8

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your work! I really liked what you did.

I just need you to do two things please:
1. Change the color of the heart from red to `#f74545`
2. there seems to be a problem in the `index.html` there's a spacing or some character after `<html>` tag so please remove it so that the `<head>` tag is right after the `<html>` tag.

**Comment by SeshaiHari** [comment]
> Thank you for your work! I really liked what you did.
> 
> I just need you to do two things please:
> 
> 1. Change the color of the heart from red to `#f74545`
> 2. there seems to be a problem in the `index.html` there's a spacing or some character after `<html>` tag so please remove it so that the `<head>` tag is right after the `<html>` tag.

Very Sorry the Error in HTML file. Now the fix has been applied.

**Comment by shahednasser** [comment]
It's ok but there still seems to be issues in the spacing in `index.html`. I'm not sure if it's because of an editor you're using.

Try to copy your work in `index.html` for the tagline, then `git checkout index.html` and try adding what you copied again. Maybe try using a different editor. If the problem persists just commit the CSS file and I will add the tagline to the HTML.

**Comment by shahednasser** [comment]
Closing this PR request due to inactivity

**Pull request closed without merging**
