### PR TITLE
Created two buttons

### PR DESCRIPTION
**Pull request by apoorvakadam**
This pull request contains two types of buttons, first is a button with **bounce animation** and the second is a **badge button** which can be used along with all the other buttons by mentioning the class of it in the span tag.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your contribution. As for the badge button I don't really see its necessity. The design looks same as basic button so please remove it.

As for the bounce button. Can you make it slower to showcase the bounce? Currently it looks like it's glitching instead of bouncing. Also make sure to place it in buttons-examples.js in the correct alphabetical order under "Animated"

**Comment by apoorvakadam** [comment]
Sure I will do the necessary changes and will revert you back.

**Comment by apoorvakadam** [comment]
I have done the necessary changes. Kindly check it and let me know.

**Comment by shahednasser** [comment]
That looks great but can you do a final change which is to make it bounce on hover instead of all the time?

**Comment by apoorvakadam** [comment]
yes sure...I will do that.

**Comment by apoorvakadam** [comment]
I have done the bounce on hover. Kindly check it and tell me if that is okay.

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @apoorvakadam for code

**Comment by apoorvakadam** [comment]
Thank you so much @shahednasser. This was the first PR request ever. Thank you for making this first experience so smooth for me.

**Comment by shahednasser** [comment]
You've done a great job for a first PR! Hopefully you can keep contributing to this repository.

**Pull request merged**
