### PR TITLE
changes

### PR DESCRIPTION
**Pull request by aparna202**
added new button- a 'plus button' icon.

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @aparna202 thank you for your work! Unfortunately, someone already worked on this and it has been crossed off the list! Please contribute to something else I'd appreciate it

**Comment by aparna202** [comment]
hey!  I had checked the "icon ideas" list and the website and it didn't have the plus icon though, so could you check it again?! Nonetheless, if it's still been done, I will work on something else thank you:)

**Comment by shahednasser** [comment]
Yes, it has been checked off. You probably saw it before someone worked on it because someone did not long ago.  I will try to find a way to make sure that a misunderstanding like this doesn't happen again!

**Comment by aparna202** [comment]
yep, just checked the website and it's there. I'm sorry for any confusion from my side:)

**Pull request closed without merging**
