### PR TITLE
sButtons footer design

### PR DESCRIPTION
**Pull request by chaitanya4vedi**
Animated gradient for footer is added. Both the timing and colour of the animation can be modified at `assets/css/index.css`.

### CODE REVIEW

**Comment by shahednasser** [comment]
I like it I think it looks good! There's one change I'd make which is I think if all the text in the footer is white it would look better.

**Comment by chaitanya4vedi** [comment]
> I like it I think it looks good! There's one change I'd make which is I think if all the text in the footer is white it would look better.

But then the texts and text with links are difficult to differentiate. So we can make  `text-decoration` of the text with link as underline. Then it will be more clear

**Comment by shahednasser** [comment]
Yes @chaitanya4vedi add underline for links and decrease the opacity of the link on hover instead of changing to blue.

**Comment by shahednasser** [comment]
Amazing work thank you!

@all-contributors please add @chaitanya4vedi for design

**Pull request merged**
