### PR TITLE
sorted 'var buttons[]'

### PR DESCRIPTION
**Pull request by mayankmohak**
Issue: Sorted buttons elements alphabetically  #99
sorted manually.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great but there are still the social buttons unsorted (google, facebook, etc...) please sort them as well.

**Comment by mayankmohak** [comment]
Sorry i thought of doing it but u haven't mentioned in #99 i thought it might affect the code.

**Comment by mayankmohak** [comment]
I thought of doing it , but it wasn't mentioned in #99

**Comment by shahednasser** [comment]
Great thank you!

@all-contributors add @mayankmohak for code

**Pull request merged**
