### PR TITLE
Logo and Footer Credits Update !

### PR DESCRIPTION
**Pull request by icoderharshit**
Added the new logo files, Updated the path for new logos(for header and navbar), and the logo icon credits in the footer as asked by you, @shahednasser :)
This suits really well to both dark and light mode theme of the website, according to me.
Looking forward to my first PR in the Hacktoberfest ! Thank you.
Please check this out @shahednasser 

• Light Mode
light
• Dark Mode
dark
•Navbar-Light
navbar-light

Issue: Find better icon similar to the logo #286

### CODE REVIEW

**Comment by shahednasser** [comment]
It looks really nice I love it! But I'm noticing the white logo is looking a little fuzzy around the text is there any way to make it look a bit more cleaner? Also, what do you suggest we should use for the favicon. I really appreciate your input on this!

You should also modify the footer credit to "Logo made by Harshit Sharma". We should also add the logo to the README and credit you there as well.

**Comment by icoderharshit** [comment]
Please Check now, @shahednasser ! I updated the logos with the requested change, made them more clear and clean. I'll be looking for some ideas on that favicon thing tomorrow morning :)

**Comment by icoderharshit** [comment]
and Thanks for having me mentioned with the proper credits, look at the Readme file @shahednasser for the credits because I couldn't figure out what text to mention along with my name there.

**Comment by shahednasser** [comment]
> and Thanks for having me mentioned with the proper credits, look at the Readme file @shahednasser for the credits because I couldn't figure out what text to mention along with my name there.

You worked hard on it so you should be credited for it! I'll look at all these changes soon and let you know if there's anything more needed. But generally it looks really good I like it!

**Comment by shahednasser** [comment]
@icoderharshit I have reviewed the changes and the white logo looks much better now! 

As for the README, Add under the logo the same credit you put at the footer of the website.

**Comment by icoderharshit** [comment]
I added the credits in the README as well, Check this out @shahednasser :) Looking forward to having these commits merged now in the master branch. If still, there's anything you'd like to change or find any issues, let me know.

**Comment by shahednasser** [comment]
Great but can you include the logo image at the top of the README?

Also, should we keep using the current favicon or do you have any replacement for it?

**Comment by icoderharshit** [comment]
Yes, surely I can. Umm, talking about the favicon; I think that needs to be replaced as well with a new and clean one. I'll look into it once this gets merged and you create a new issue for it, I guess. That' ll be really better for all the open-source contributors, maybe we find or look up to more ideas from different people. That's my say, final word would be yours @shahednasser :)

**Comment by shahednasser** [comment]
@icoderharshit sure I don't mind. I'll merge this PR once you update the README with the logo

**Comment by icoderharshit** [comment]
Check this out @shahednasser , did all that you asked to :)

**Comment by icoderharshit** [comment]
Great, I think there are no more conflicts with the base branch ! Thanks for the assistance @shahednasser , Finally is it ready to be done? so, that I can start looking to favicon thing.

**Comment by shahednasser** [comment]
Great work thank you so much! I'll open the issue for favicon as you requested.

**Comment by icoderharshit** [comment]
Hey @shahednasser , please add the required label "hacktoberfest" for this issue, as I need to mark this contribution there :) or tell me, if this isn't necessary or something because I am a little confused for this.
Regards.

**Comment by shahednasser** [comment]
Hello @icoderharshit the PR or issue don't need a hacktoberfest label, the only thing required is for the repository to either have the "hacktoberfest" topic (which we have) or for the PR to be labeled "hacktoberfest-accepted". So you don't have anything to worry about. The only PRs that wouldn't be accepted in this repo are the ones labeled "invalid"

**Comment by shahednasser** [comment]
You can read more about it in the [Hacktoberfest FAQ](https://hacktoberfest.digitalocean.com/faq)

**Pull request merged**
