### PR TITLE
Updated text in How to Use section

### PR DESCRIPTION
**Pull request by ashleypean**
Signed-off-by: Ashley Pean <pean.ashley@gmail.com>

Issue: Update text in the How to Use section

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great work! But can you please pull from the master branch, as it is behind and some problems we fixed have reappeared. Just make sure your branch is up to date then commit the changes

**Comment by ashleypean** [comment]
I'm having some trouble committing the changes. I was able to update my branch using the CLI commands below: 
```
git checkout <my-branch>
git fetch origin
git merge origin/master
```

When I try to commit the changes I get the error message: nothing to commit, working tree clean

**Comment by shahednasser** [comment]
You should try the following
```
git checkout <my-branch>
git pull origin master
git add .
git commit -m "branch up to date"
git push origin <my-branch>
```

let me know if it works.

**Comment by ashleypean** [comment]
Doesn't seem to have worked. I'm still getting the message that my branch is up to date.

**Comment by shahednasser** [comment]
I'm sorry if this is an inconvenience but I think the easiest solution is if you fork the repository again and add your changes.

**Pull request closed without merging**
