### PR TITLE
Added hamburger 

### PR DESCRIPTION
**Pull request by valeriaoshiro**
Added hamburger for mobile devices

Issue: #7

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great work!

1. Please add the following style rules to `.sidebar` on small devices:
```
    position: fixed;
    left: 0;
    top: 0;
    height: 100%;
    padding: 20px;
    width: 70%;
    box-shadow: 1px 1px 5px #8a8a8a;
```

2. When the user toggles the sidebar they can't close it. Can you add an event listener to clicking outside the sidebar so that it slides out? Or if it's easier, add a close button at the top of the sidebar (that only shows on smaller screens) and on clicking the X the sidebar would slide out.
3. make font size of `.sidebar a` on small devices `1.3rem`

**Comment by valeriaoshiro** [comment]
Made the changes requested. Please review. Thank you

**Review by shahednasser — CHANGES_REQUESTED** [review]
It all looks good. There's one last bug:  
When scrolling, `.scrolling` is added to `.sidebar` and it sets top to 90px. This is important on large screens but on smaller screens it doesn't look good. So just add a rule for when `max-width` is 767px, add the following rules for `.sidebar.scrolling`:
```
top: 0;
z-index: 100;
```

**Comment by valeriaoshiro** [comment]
Hi, I added the changes. Please review. Thank you

**Comment by shahednasser** [comment]
Great work! Thank you

@all-contributors please add @valeriaoshiro for code

**Pull request merged**
