### PR TITLE
Chaitanya sbuttons

### PR DESCRIPTION
**Pull request by chaitanya4vedi**
Fix watch command & Logo Added
watch for both less and sass for any changes anywhere included. lite-server added for live updates of the page
`npm install` to install all dependencies
`npm start` will compile,build and run the project in lite-server updating changes in live
Added Logos together with few alternatives

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @chaitanya4vedi thank you for the great work!

Can you please split the work for the two issues into two pull requests? i.e. keep this issue for fixing the watch command, remove the changes related to the logo and add them to a new issue. It's better to keep track of everything.

I'll edit the title as well to make it more related to the watch issue.

**Comment by shahednasser** [comment]
Also, there are changes in files like .idea, cache etc... if you can remove those changes from the pull request it would be great!

**Comment by chaitanya4vedi** [comment]
new pull request created for watch and logo individually

**Comment by chaitanya4vedi** [comment]
Done

**Pull request closed without merging**
