### PR TITLE
Add hamburger button with functionality

### PR DESCRIPTION
**Pull request by valeriaoshiro**
* Whenever the screen is smaller than 768px of width, the sidebar disappears and there is a hamburger button instead. 
* The hamburger button triggers the sidebar. 
* If the sidebar is open and the user scrolls, the sidebar disappears. 
* The hamburger buttons stays at the top of the page, not the viewport.
* The hamburger button doesn't show when the screen is bigger than 768px

Issue: Add hamburger side menu on mobile devices #7

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hi there! Thank you for your work.

There are some issues you need to fix:
1. the classes for `sidebar-toggler` for display should be `d-md-none d-block`. Currently it's not appearing on small screens.
2. Please put the sidebar toggler in the `navbar` before `logo`
3. Add a CSS rule for `.navbar:not(.scrolling) .scrolling-toggler` color should be `#fff`
4. Add a CSS rule for `.navbar.scrolling .scrolling-toggler` color should be `#3A91FF`
5. Remove border for the hamburger button
6. Currently, clicking on the hamburger button does nothing. It should slide in from the left. You can use a library like [animate.css](https://animate.style/) if that's easier. I don't mind.

**Comment by valeriaoshiro** [comment]
I'm sorry, I think I did something wrong. I don't know why I can see everybody's changes in my branch

**Comment by shahednasser** [comment]
@valeriaoshiro  It's ok! If it's not a hassle please clone the current master branch again and add your changes to it, then create a new pull request. I'm not sure what happened but I can't merge this pull request the way it is.  
If it's a hassle and you would like to not do this issue anymore, let me know.

**Comment by valeriaoshiro** [comment]
You can reassign the issue to another person. Thank you!

**Comment by hrithiksh101** [comment]
i have made some commits but i'm not sure if the commits have actually happened or not , can you review it

**Comment by shahednasser** [comment]
Hi @hrithiksh101 . Please create a pull request to send your changes. Please read the [contribution guide](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md) to learn how you can do that.

**Pull request closed without merging**
