### PR TITLE
Create ripple button

### PR DESCRIPTION
**Pull request by martin-garcia-blanco**
Hello 🤘🏼
I wanted to help this project and I contributed with the implementation of a button with a ripple effect.

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @martin-garcia-blanco thank you for contributing!

I need you to do two things for me:
1. You need to compile the code for me to see the changes in the website. to do that, please run `npm run compile` then commit the changes in `dist/sbuttons.min.css` and `dist/sbuttons.css`
2. You need to check off "ripple button" in the buttons ideas file. Learn more about how to do it [here](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md#button-ideas)

**Comment by martin-garcia-blanco** [comment]
> Hi @martin-garcia-blanco thank you for contributing!
> 
> I need you to do two things for me:
> 
>     1. You need to compile the code for me to see the changes in the website. to do that, please run `npm run compile` then commit the changes in `dist/sbuttons.min.css` and `dist/sbuttons.css`
> 
>     2. You need to check off "ripple button" in the buttons ideas file. Learn more about how to do it [here](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md#button-ideas)

I thought it was not necessary but it's fixed now.

**Comment by shahednasser** [comment]
Issue has been resolved by #250 . Thank you for your work!

@all-contributors please add @martin-garcia-blanco for code

**Comment by martin-garcia-blanco** [comment]
> #250

Hello maybe I didn't understand good the idea of ripple effect, my implementation is really similar to material ui onClick effect
https://material-ui.com/es/components/buttons/
that is totally different to the current implementation.
If you want maybe its posible to create a new effect with this implementation, or not, as you want.

Thanks   🤘🏼

**Comment by shahednasser** [comment]
@martin-garcia-blanco I see. If you can, please create a new pull request but name the button "Material Ui" button

**Pull request closed without merging**
