### PR TITLE
Hamburger menu added for the mobile screens

### PR DESCRIPTION
**Pull request by hrithiksh101**
if the screen goes  below 768px then
habmurger menu appears on the left side of the screen , this menu is fixed no matter how much the user scrolls .

Issue:

### CODE REVIEW

**Comment by hrithiksh101** [comment]
decrease the screen width below 768px to see the change

**Comment by shahednasser** [comment]
Thank you for your work! Unfortunately, there seems to be a problem in the website. Maybe a wrong closed HTML tag or something? Please try testing it again and check.

**Comment by hrithiksh101** [comment]
ok i guess there is some problems with the comments , i will re-update my work

**Comment by hrithiksh101** [comment]
is it ok now ?

**Comment by hrithiksh101** [comment]
i have re-updated the code and resolved the issue.

**Comment by hrithiksh101** [comment]
i have checked the code but i don't know for some reasons whenever i commit it to this repository , there appears some comments automatically which are may be computer generated , like changesbyhrithik or ------------------master
but I have checked the site on my end , and used online tools to verify any syntax error or closing or missing tag , the code updated by me completely fine without any errors and website runs on my end completely fine .
i don't know what exactly is the issue .

well Thank you for giving me opportunity to work for this open source project . 😃

**Comment by shahednasser** [comment]
it's ok @hrithiksh101 . The issue has been resolved by someone else. Thank you! If you would like to take on other issues in the repo then go ahead!

**Pull request closed without merging**
