### PR TITLE
Get Started page

### PR DESCRIPTION
**Pull request by nicholedwight**
Solves this issue: https://github.com/shahednasser/sbuttons/issues/391

I created a Get Started page with the same theme as the homepage. I copied over the missing Installation and Usage instructions from our Readme and reformatted the html around existing instructions.

I removed the original How To Use section from the homepage along with the secondary-hr that was used to separate the sections.

I added an example button next to Basic, Disabled, and Icon buttons.

On the Get Started page, the logo at the top is also a link back to the homepage. There is also an "Examples" button where the original link to current page was - I wanted to make use of this space to link back to examples of buttons.

Let me know if you want me to make any additions or changes!!

✨

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your work you've done a great job! I just would make some changes:

1. Can you add a sidebar menu, just like in the home page and the links should be the different sections in the page (Installation, Download CSS file, etc...) To keep the same functionality make sure to add `index.js`, `sidebar.css` and `index.css` in the HTML.
2. Can you align everything to the left rather than center? I think it would look better that way.

That's all. Thank you!

**Comment by nicholedwight** [comment]
Of course! I'll have all that done shortly :)

**Review by shahednasser — CHANGES_REQUESTED** [review]
1. For "Installation" please change it from h1 to h2. Same thing for Usage.
2. Please align Installation and usage to the left as well.
3. Please add class name "secondary-hr" to all hr elements
4. Instead of using "div" for "instruction-block"'s can you use "section"?
5. Add "Installation" and "Usage" as the main menu items with the rest as their children respectively.

**Comment by nicholedwight** [comment]
My latest commit changed the two <h1>'s into <h2>'s, aligned Installation and Usage to the left, added the "secondary-hr" class to all new <hr />'s, made use of <section> in place of <div>'s on all instruction-blocks, and added the submenu links :)

**Comment by shahednasser** [comment]
It all looks good but for some reason the footer is boxed now. This could be to wrong closing of html tags can you check that please?

**Comment by nicholedwight** [comment]
Oh! I'm so sorry! Just a moment!

**Comment by shahednasser** [comment]
Alright great work! Thank you.

@all-contributors please add @nicholedwight for code, design and content

**Pull request merged**
